-- Create a table to store user's favorite menu items
CREATE TABLE public.user_favorite_dishes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  menu_item_id INTEGER NOT NULL, -- Corresponds to the hardcoded ID in the frontend
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT unique_user_favorite UNIQUE (user_id, menu_item_id)
);

-- Enable Row Level Security
ALTER TABLE public.user_favorite_dishes ENABLE ROW LEVEL SECURITY;

-- Policies for the favorites table
CREATE POLICY "Users can view their own favorite dishes."
ON public.user_favorite_dishes
FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can manage their own favorite dishes."
ON public.user_favorite_dishes
FOR ALL -- Covers INSERT, UPDATE, DELETE
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);
